# Generated by Django 5.0.3 on 2024-03-28 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Labelinfo', '0002_remove_labelinfo_id_alter_labelinfo_handlingunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('Matricule', models.CharField(max_length=100)),
                ('Storage_Location', models.CharField(max_length=100)),
                ('Storage_Bin', models.CharField(max_length=100)),
                ('Material_Number', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('date_transaction', models.DateField()),
                ('hour_transaction', models.TimeField()),
                ('Message', models.CharField(choices=[('Scanned', 'Scanned'), ('Already scanned', 'Already scanned'), ('Added manually', 'Added manually')], max_length=20)),
                ('HandlingUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Labelinfo.labelinfo')),
            ],
        ),
    ]
