# Generated by Django 5.0.3 on 2024-03-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labelinfo', '0002_remove_labelinfo_id_alter_labelinfo_handlingunit'),
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('HandlingUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Labelinfo.labelinfo')),
                ('storage_location', models.CharField(max_length=255)),
                ('storage_bin', models.CharField(max_length=255)),
                ('material_number', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('date_transaction', models.DateField()),
                ('hour_transaction', models.TimeField()),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
