# Generated by Django 5.0.3 on 2024-03-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_transaction_matricule_transaction_id_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='message',
            field=models.CharField(choices=[('Scanned', 'Added Manually')], max_length=20),
        ),
    ]
