# Generated by Django 5.0.3 on 2024-04-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0004_alter_transaction_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
