# Generated by Django 5.0.3 on 2024-04-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0005_rename_quantity_transaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='message',
            field=models.CharField(choices=[('Scanned', 'Scanned'), ('Added Manually', 'Added Manually')], max_length=20),
        ),
    ]
