# Generated by Django 5.0.3 on 2024-04-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0007_alter_transaction_handlingunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Scanned_handling_unit',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
