# Generated by Django 5.0.3 on 2024-04-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0010_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Scanned_handling_unit',
            field=models.CharField(max_length=20),
        ),
    ]
