# Generated by Django 4.2 on 2024-04-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0012_alter_transaction_scanned_handling_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='HandlingUnit',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
