# Generated by Django 4.2 on 2024-04-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0013_alter_transaction_handlingunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Scanned_handling_unit',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
