# Generated by Django 4.2 on 2024-04-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0015_alter_transaction_matricule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='material_number',
            new_name='Material_Number',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='storage_bin',
            new_name='Storage_Bin',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='storage_location',
            new_name='Storage_Location',
        ),
    ]
