# Generated by Django 4.2 on 2024-04-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0016_rename_material_number_transaction_material_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_transaction',
            new_name='Date_transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='hour_transaction',
            new_name='Hour_transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='message',
            new_name='Message',
        ),
    ]
