# Generated by Django 4.2 on 2024-04-18 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Transactions', '0017_rename_date_transaction_transaction_date_transaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Date_transaction',
            new_name='date_transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Hour_transaction',
            new_name='hour_transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Material_Number',
            new_name='material_number',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Storage_Bin',
            new_name='storage_bin',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Storage_Location',
            new_name='storage_location',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Matricule',
            field=models.ForeignKey(default='123456', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
