# Generated by Django 4.2 on 2024-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0019_alter_transaction_matricule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
