# Generated by Django 4.2 on 2024-05-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0023_alter_transaction_handlingunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='HandlingUnit',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Quantity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_transaction',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hour_transaction',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='message',
            field=models.CharField(choices=[('Scanned', 'Scanned'), ('Added Manually', 'Added Manually')], max_length=20),
        ),
    ]
