# Generated by Django 4.2 on 2024-05-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0026_alter_transaction_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='location_type',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
