# Generated by Django 4.2 on 2024-05-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0027_transaction_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='location_type',
            field=models.CharField(choices=[('WH', 'WH'), ('SM', 'SM')], default='WH', max_length=2),
        ),
    ]
