# Generated by Django 4.2 on 2024-06-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0028_alter_transaction_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='message',
            field=models.CharField(choices=[('Scanned', 'Scanned'), ('Added Manually', 'Added Manually'), ('Position Changed', 'Position Changed'), ('Quantity Changed', 'Quantity Changed'), ('Position and Quantity Changed', 'Position and Quantity Changed')], max_length=200),
        ),
    ]
