# Generated by Django 4.2 on 2024-06-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0032_alter_transaction_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Quantity',
            field=models.IntegerField(max_length=6),
        ),
    ]
