# Generated by Django 4.2 on 2024-06-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0034_labelinfo_alter_transaction_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Labelinfo',
        ),
    ]
