# Generated by Django 4.2 on 2024-06-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0035_delete_labelinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='message',
            field=models.CharField(choices=[('Scanned', 'Scanned'), ('Added Manually', 'Added Manually'), ('Position Changed', 'Position Changed'), ('Quantity Changed', 'Quantity Changed'), ('Position Not Changed', 'Position Not Changed')], max_length=20),
        ),
    ]
