# Generated by Django 4.2 on 2024-04-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labelinfo', '0002_remove_labelinfo_id_alter_labelinfo_handlingunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelinfo',
            name='Quantity',
            field=models.CharField(max_length=225),
        ),
    ]
