# Generated by Django 4.2 on 2024-04-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labelinfo', '0003_alter_labelinfo_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelinfo',
            name='Quantity',
            field=models.FloatField(max_length=225),
        ),
    ]
