# Generated by Django 4.2 on 2024-06-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labelinfo', '0007_alter_labelinfo_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelinfo',
            name='Quantity',
            field=models.CharField(max_length=100),
        ),
    ]
